// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhsssgugezrwpjprnpuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoc3NzZ3VnZXpyd3BqcHJucHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODIwNjksImV4cCI6MjA2Njk1ODA2OX0.Va94O5rL1VdyTyCeG4tqS8yy9kyQtpmP1j5vtU9RIus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});